services:
  build_src: &BASE_APP
    image: days_build
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env.example
    volumes:
      - .:/app
      - $HOME/.cache/days:/root/.cache/pypoetry
  api:
    <<: *BASE_APP
    command: ["api-dev"]
    depends_on: [ "db" ]
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: days
      MYSQL_DATABASE: days_db
      MYSQL_USER: days
      MYSQL_PASSWORD: days
    volumes:
      - ./dbdata:/var/lib/mysql/